
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; --- Configuración de Hardware N16R8 ---
board_build.arduino.memory_type = qio_opi ; Habilita la PSRAM Octal (la R8 de tu chip)
board_build.flash_mode = qio              ; Modo de acceso rápido a la memoria Flash
board_upload.flash_size = 16MB            ; Tamaño real de tu memoria (la N16 de tu chip)
board_build.partitions = default_16MB.csv ; Define cómo repartir esos 16MB

; --- Comunicación y Debug ---
monitor_speed = 115200

; --- Librerías del Proyecto (Dependencies) ---
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    bblanchon/ArduinoJson @ ^7.0.0
    knolleary/PubSubClient @ ^2.8

; Cómo: 'build_unflags' le dice a PlatformIO que busque estas definiciones 
; en la configuración por defecto de la placa y las ELIMINE.
build_unflags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; Cómo: Ahora las definimos nosotros en 0 sin que nadie se queje.
; Importante: No dejes espacio entre el -D y el nombre (ej: -DARDUINO...)
build_flags = 
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0